RGB=imread('/img/photo.tif');%读取图像
whos
imshow(RGB);
title('photo.tif');
imfinfo('photo.tif');
imwrite(RGB,'/img/photo.jpg');
imwrite(RGB,'/img/photo.bmp');
I=imread('/img/Pepper.bmp');
J=imread('/img/photo.bmp');
imfinfo('Pepper.bmp');
imfinfo('photo.bmp');
figure,imshow(I);
title('Pepper.bmp');
figure,imshow(J);
title('photo.bmp');
BW=im2bw(I,0.4);
imshow(BW);
title('灰度图像转化为二值图像');