# Project: 项目3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = TESTscan.o TESTparse.o ../09语义分析(VC)/TESTmain.o
LINKOBJ  = TESTscan.o TESTparse.o ../09语义分析(VC)/TESTmain.o
LIBS     = -L"D:/Dev-Cpp/MinGW64/lib" -L"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/Dev-Cpp/MinGW64/include" -I"D:/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 项目3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

TESTscan.o: TESTscan.c
	$(CPP) -c TESTscan.c -o TESTscan.o $(CXXFLAGS)

TESTparse.o: TESTparse.c
	$(CPP) -c TESTparse.c -o TESTparse.o $(CXXFLAGS)

../09语义分析(VC)/TESTmain.o: ../09语义分析(VC)/TESTmain.c
	$(CPP) -c ../09语义分析(VC)/TESTmain.c -o ../09语义分析(VC)/TESTmain.o $(CXXFLAGS)
